version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  target-branch: "develop"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  rebase-strategy: "auto"
  labels:
    - "security"
    - "dependencies"
- package-ecosystem: composer
  directory: "/"
  target-branch: "develop"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  rebase-strategy: "auto"
  labels:
    - "security"
    - "dependencies"
